# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: List dir
        run: |
          ls -ltr
          pwd
        
      - name: Print name
        run: echo "$(date)"
  windows:
    runs-on: windows-latest
    steps:
      - name: Print date
        run: Get-Date
  macos:
    runs-on: macos-latest
    steps:
      - name: Print date
        run: echo "$(date)"
  wrapup:
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, macos]
    steps:
      - name: print date
        run: echo date
